export default function(){
  this.transition(
    this.fromRoute('index'),
    this.toRoute('about'),
    this.toRoute('projects'),
    this.toRoute('repositories'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.fromRoute('about'),
    this.toRoute('index'),
    this.toRoute('projects'),
    this.toRoute('repositories'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.fromRoute('projects'),
    this.toRoute('index'),
    this.toRoute('repositories'),
    this.toRoute('about'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.fromRoute('repositories'),
    this.toRoute('index'),
    this.toRoute('projects'),
    this.toRoute('about'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
}
